### PR TITLE
Grades

### PR DESCRIPTION
**Pull request by basictom**

### CODE REVIEW

**Comment by basictom** [comment]
Stuck on this for loop. I keep getting 'gradeB' not defined. If gradeB cannot be defined, why wouldn't that same error get flagged for 'gradeF' 'gradeD' 'gradeC'???
@utleroy

**Comment by utleroy** [comment]
You are getting not defined because none of your variables(i.e. gradeA, gradeB etc.) is defined outside of your "for" loop. You have to define them first so that you can pass the expected result through said variable so that when you console.log(gradeF), the console.log knows what to look for. In other words if you define a variable inside of a "for" loop, that variable is not global and is only accessible inside of the loop. Let me know if this helps...

**Comment by utleroy** [comment]
also just glancing over your code, you should make sure that all of your brackets are opened and closed. hint... you might have an extra closing bracket somewhere.

**Comment by utleroy** [comment]
Looks good! 1 side note... You might want to add a description to your console.log(s) so that when someone(or yourself) runs your code it is more readable. For example console.log("the lowest score is: ,"sortScores.shift());

**Comment by utleroy** [comment]
correction...console.log("the lowest score is: ",sortScores.shift()); Sorry, I had the comma in the wrong place

**Comment by utleroy** [comment]
👍

**Pull request merged**
